name: Change Federation Status of Server
description: |
  This issue type is for adding or removing servers from federating with Hachyderm.
labels: ["Domain Block Request or Report"]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️  Please Read Before Proceeding ⚠️
        Before filing this report, please review our [Blocklist Documentation Page](https://community.hachyderm.io/docs/moderation/blocklists/).
        This doc page includes expectation setting for how servers are added/removed and how much transparency to expect.

        If this domain needs to be brought to our attention in a non-public venue, please file a report using either the Mastodon
        UI or email us directly. For information about this, please read our [Reporting Documentation Page](https://community.hachyderm.io/docs/moderation/reporting/).
  - type: textarea
    attributes:
      label: |
        What domain(s) need to be added or removed from our blocklist?
      description: |
        Please include as much context as possible, even if it seems obvious.
    validations:
      required: true

