name: Third Party Mastodon Tools
description: |
  This issue type is specifically for suggesting third party tools to use with Mastodon
  as deployed and run on Hachyderm.
labels: ["Suggestions"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reaching out to us! Please make sure this is a new suggestion
        before proceeding.

        Please note that we cannot currently accept tooling suggestions that require
        us to fork from the main Mastodon project.
  - type: textarea
    attributes:
      label: |
        What is your suggestion?
      description: |
        Use as much detail and context about the tool(s) as possible.
    validations:
      required: true

